function Players(row,colom,kind,type){
  this.row=row;
  this.colom=colom;
  this.kind=kind;
  this.type=type;
  this.color=null;
  if(this.kind=='BLACK'){
    if(this.type=='Horse'){
      this.color=loadImage("BlackHorse.png");
    }
    if(this.type=='King'){
      this.color=loadImage("BlackKing.png");
    }
    if(this.type=='Queen'){
      this.color=loadImage("BlackQueen.png");
    }
    if(this.type=='Runer'){
      this.color=loadImage("BlackRuner.png");
    }
    if(this.type=='Soldier'){
      this.color=loadImage("BlackSolider.png");
    }
    if(this.type=='Steeple'){
      this.color=loadImage("BlackSteeple.png");
    }
  }
  else{
    if(this.type=='Horse'){
      this.color=loadImage("WhiteHorse.png");
    }
    if(this.type=='King'){
      this.color=loadImage("WhiteKing.png");
    }
    if(this.type=='Queen'){
      this.color=loadImage("WhiteQueen.png");
    }
    if(this.type=='Runer'){
      this.color=loadImage("WhiteRuner.png");
    }
    if(this.type=='Soldier'){
      this.color=loadImage("WhiteSolider.png");
    }
    if(this.type=='Steeple'){
      this.color=loadImage("WhiteSteeple.png");
    }
  }
  this.movingOpsions=function(){
    posibalLocations=[]
    if(this.kind=='BLACK'){
      if(this.type=='Horse'){
        posibalLocations=[]
        if((this.row>1&&this.colom<7)&&(bord[this.row-2][this.colom+1]==null||bord[this.row-2][this.colom+1].kind=='WHITE')){
          posibalLocations.push([this.row-2,this.colom+1])
        }
        if((this.row>1&&this.colom>0)&&(bord[this.row-2][this.colom-1]==null||bord[this.row-2][this.colom-1].kind=='WHITE')){
          posibalLocations.push([this.row-2,this.colom-1])
        }
        if((this.row<6&&this.colom<7)&&(bord[this.row+2][this.colom+1]==null||bord[this.row+2][this.colom+1].kind=='WHITE')){
          posibalLocations.push([this.row+2,this.colom+1])
        }
        if((this.row<6&&this.colom>0)&&(bord[this.row+2][this.colom-1]==null||bord[this.row+2][this.colom-1].kind=='WHITE')){
          posibalLocations.push([this.row+2,this.colom-1])
        }
        if((this.row<7&&this.colom>1)&&(bord[this.row+1][this.colom-2]==null||bord[this.row+1][this.colom-2].kind=='WHITE')){
          posibalLocations.push([this.row+1,this.colom-2])
        }
        if((this.row<7&&this.colom<6)&&(bord[this.row+1][this.colom+2]==null||bord[this.row+1][this.colom+2].kind=='WHITE')){
          posibalLocations.push([this.row+1,this.colom+2])
        }
        if((this.row>0&&this.colom>1)&&(bord[this.row-1][this.colom-2]==null||bord[this.row-1][this.colom-2].kind=='WHITE')){
          posibalLocations.push([this.row-1,this.colom-2])
        }
        if((this.row>0&&this.colom<6)&&(bord[this.row-1][this.colom+2]==null||bord[this.row-1][this.colom+2].kind=='WHITE')){
          posibalLocations.push([this.row-1,this.colom+2])
        }
      }
      if(this.type=='King'){
        posibalLocations=[]
        if((this.row>0)&&(bord[this.row-1][this.colom]==null||(bord[this.row-1][this.colom]!=null&&bord[this.row-1][this.colom].kind=='WHITE'))){
            posibalLocations.push([this.row-1,this.colom])
        }
        if((this.row>0&&this.colom>0)&&(bord[this.row-1][this.colom-1]==null||(bord[this.row-1][this.colom-1]!=null&&bord[this.row-1][this.colom-1].kind=='WHITE'))){
            posibalLocations.push([this.row-1,this.colom-1])
        }
        if((this.row>0&&this.colom<7)&&(bord[this.row-1][this.colom+1]==null||(bord[this.row-1][this.colom+1]!=null&&bord[this.row-1][this.colom+1].kind=='WHITE'))){
            posibalLocations.push([this.row-1,this.colom+1])
        }
        if((this.row<7)&&(bord[this.row+1][this.colom]==null||(bord[this.row+1][this.colom]!=null&&bord[this.row+1][this.colom].kind=='WHITE'))){
            posibalLocations.push([this.row+1,this.colom])
        }
        if((this.row<7&&this.colom>0)&&(bord[this.row+1][this.colom-1]==null||(bord[this.row+1][this.colom-1]!=null&&bord[this.row+1][this.colom-1].kind=='WHITE'))){
            posibalLocations.push([this.row+1,this.colom-1])
        }
        if((this.row<7&&this.colom<7)&&(bord[this.row+1][this.colom+1]==null||(bord[this.row+1][this.colom+1]!=null&&bord[this.row+1][this.colom+1].kind=='WHITE'))){
            posibalLocations.push([this.row+1,this.colom+1])
        }
        if((this.colom<7)&&(bord[this.row][this.colom+1]==null||(bord[this.row][this.colom+1]!=null&&bord[this.row][this.colom+1].kind=='WHITE'))){
            posibalLocations.push([this.row,this.colom+1])
        }
        if((this.colom>0)&&(bord[this.row][this.colom-1]==null||(bord[this.row][this.colom-1]!=null&&bord[this.row][this.colom-1].kind=='WHITE'))){
            posibalLocations.push([this.row,this.colom-1])
        }
      }
      if(this.type=='Queen'){
        posibalLocations=[]
        for(let i=this.row+1,j=this.colom+1;i<8&&j<8;i++,j++){
          if(bord[i][j]!=null&&bord[i][j].kind=='WHITE'){
            posibalLocations.push([i,j])
            break;
          }
          if(bord[i][j]!=null)
            break;
          posibalLocations.push([i,j])
        }  
        for(let i=this.row-1,j=this.colom-1;i>=0&&j>=0;i--,j--){
          if(bord[i][j]!=null&&bord[i][j].kind=='WHITE'){
            posibalLocations.push([i,j])
            break;
          }
          if(bord[i][j]!=null)
            break;
          posibalLocations.push([i,j])
        }
        for(let i=this.row+1,j=this.colom-1;i<8&&j>=0;i++,j--){
          if(bord[i][j]!=null&&bord[i][j].kind=='WHITE'){
            posibalLocations.push([i,j])
            break;
          }
          if(bord[i][j]!=null)
            break;
          posibalLocations.push([i,j])
        }
        for(let i=this.row-1,j=this.colom+1;i>=0&&j<8;i--,j++){
          if(bord[i][j]!=null&&bord[i][j].kind=='WHITE'){
            posibalLocations.push([i,j])
            break;
          }
          if(bord[i][j]!=null)
            break;
          posibalLocations.push([i,j])
        }
        for(let i=this.colom+1;i<8;i++){
          if(bord[this.row][i]!=null){
            if(bord[this.row][i].kind=='WHITE'){
                posibalLocations.push([this.row,i])
              break;
            } 
              break;
          }
          posibalLocations.push([this.row,i])
        }
        for(let i=this.colom-1;i>=0;i--){
          if(bord[this.row][i]!=null){
            if(bord[this.row][i].kind=='WHITE'){
                posibalLocations.push([this.row,i])
              break;
            } 
              break;
          }
          posibalLocations.push([this.row,i])
        }
        for(let i=this.row+1;i<8;i++){
          if(bord[i][this.colom]!=null){
            if(bord[i][this.colom].kind=='WHITE'){
                posibalLocations.push([i,this.colom])
              break;
            } 
              break;
          }
          posibalLocations.push([i,this.colom])
        }
        for(let i=this.row-1;i>=0;i--){
          if(bord[i][this.colom]!=null){
            if(bord[i][this.colom].kind=='WHITE'){
                posibalLocations.push([i,this.colom])
              break;
            } 
              break;
          }
          posibalLocations.push([i,this.colom])
        }
      }
      if(this.type=='Runer'){
        posibalLocations=[]
        for(let i=this.row+1,j=this.colom+1;i<8&&j<8;i++,j++){
          if(bord[i][j]!=null&&bord[i][j].kind=='WHITE'){
            posibalLocations.push([i,j])
            break;
          }
          if(bord[i][j]!=null)
            break;
          posibalLocations.push([i,j])
        }  
        for(let i=this.row-1,j=this.colom-1;i>=0&&j>=0;i--,j--){
          if(bord[i][j]!=null&&bord[i][j].kind=='WHITE'){
            posibalLocations.push([i,j])
            break;
          }
          if(bord[i][j]!=null)
            break;
          posibalLocations.push([i,j])
        }
        for(let i=this.row+1,j=this.colom-1;i<8&&j>=0;i++,j--){
          if(bord[i][j]!=null&&bord[i][j].kind=='WHITE'){
            posibalLocations.push([i,j])
            break;
          }
          if(bord[i][j]!=null)
            break;
          posibalLocations.push([i,j])
        }
        for(let i=this.row-1,j=this.colom+1;i>=0&&j<8;i--,j++){
          if(bord[i][j]!=null&&bord[i][j].kind=='WHITE'){
            posibalLocations.push([i,j])
            break;
          }
          if(bord[i][j]!=null)
            break;
          posibalLocations.push([i,j])
        }
      }
      if(this.type=='Soldier'){
        posibalLocations=[]
        if(this.row==1){
          if((this.row<6)&&bord[this.row+1][this.colom]==null&&bord[this.row+2][this.colom]==null){
            posibalLocations.push([this.row+2,this.colom])
          }
        }
        if((this.row<7&&this.colom<7)&&bord[this.row+1][this.colom+1]!=null&&bord[this.row+1][this.colom+1].kind=='WHITE'){
          posibalLocations.push([this.row+1,this.colom+1])
        }
        if((this.row<7&&this.colom>0)&&bord[this.row+1][this.colom-1]!=null&&bord[this.row+1][this.colom-1].kind=='WHITE'){
          posibalLocations.push([this.row+1,this.colom-1])
        }
        if((this.row<7)&&bord[this.row+1][this.colom]==null){
            posibalLocations.push([this.row+1,this.colom])
        }
      }
      if(this.type=='Steeple'){
        posibalLocations=[]
        for(let i=this.colom+1;i<8;i++){
          if(bord[this.row][i]!=null){
            if(bord[this.row][i].kind=='WHITE'){
              posibalLocations.push([this.row,i])
              break;
            } 
              break;
          }
          posibalLocations.push([this.row,i])
        }
        for(let i=this.colom-1;i>=0;i--){
          if(bord[this.row][i]!=null){
            if(bord[this.row][i].kind=='WHITE'){
              posibalLocations.push([this.row,i])
              break;
            } 
              break;
          }
          posibalLocations.push([this.row,i])
        }
        for(let i=this.row+1;i<8;i++){
          if(bord[i][this.colom]!=null){
            if(bord[i][this.colom].kind=='WHITE'){
              posibalLocations.push([i,this.colom])
              break;
            } 
              break;
          }
          posibalLocations.push([i,this.colom])
        }
        for(let i=this.row-1;i>=0;i--){
          if(bord[i][this.colom]!=null){
            if(bord[i][this.colom].kind=='WHITE'){
              posibalLocations.push([i,this.colom])
              break;
            } 
              break;
          }
          posibalLocations.push([i,this.colom])
        }
      }
    }
    else{
      if(this.type=='Horse'){
        posibalLocations=[]
        if((this.row>1&&this.colom<7)&&(bord[this.row-2][this.colom+1]==null||bord[this.row-2][this.colom+1].kind=='BLACK')){
          posibalLocations.push([this.row-2,this.colom+1])
        }
        if((this.row>1&&this.colom>0)&&(bord[this.row-2][this.colom-1]==null||bord[this.row-2][this.colom-1].kind=='BLACK')){
          posibalLocations.push([this.row-2,this.colom-1])
        }
        if((this.row<6&&this.colom<7)&&(bord[this.row+2][this.colom+1]==null||bord[this.row+2][this.colom+1].kind=='BLACK')){
          posibalLocations.push([this.row+2,this.colom+1])
        }
        if((this.row<6&&this.colom>0)&&(bord[this.row+2][this.colom-1]==null||bord[this.row+2][this.colom-1].kind=='BLACK')){
          posibalLocations.push([this.row+2,this.colom-1])
        }
        if((this.row<7&&this.colom>1)&&(bord[this.row+1][this.colom-2]==null||bord[this.row+1][this.colom-2].kind=='BLACK')){
          posibalLocations.push([this.row+1,this.colom-2])
        }
        if((this.row<7&&this.colom<6)&&(bord[this.row+1][this.colom+2]==null||bord[this.row+1][this.colom+2].kind=='BLACK')){
          posibalLocations.push([this.row+1,this.colom+2])
        }
        if((this.row>0&&this.colom>1)&&(bord[this.row-1][this.colom-2]==null||bord[this.row-1][this.colom-2].kind=='BLACK')){
          posibalLocations.push([this.row-1,this.colom-2])
        }
        if((this.row>0&&this.colom<6)&&(bord[this.row-1][this.colom+2]==null||bord[this.row-1][this.colom+2].kind=='BLACK')){
          posibalLocations.push([this.row-1,this.colom+2])
        }
      }
      if(this.type=='King'){
        posibalLocations=[]
        if((this.row>0)&&(bord[this.row-1][this.colom]==null||(bord[this.row-1][this.colom]!=null&&bord[this.row-1][this.colom].kind=='BLACK'))){
            posibalLocations.push([this.row-1,this.colom])
        }
        if((this.row>0&&this.colom>0)&&(bord[this.row-1][this.colom-1]==null||(bord[this.row-1][this.colom-1]!=null&&bord[this.row-1][this.colom-1].kind=='BLACK'))){
            posibalLocations.push([this.row-1,this.colom-1])
        }
        if((this.row>0&&this.colom<7)&&(bord[this.row-1][this.colom+1]==null||(bord[this.row-1][this.colom+1]!=null&&bord[this.row-1][this.colom+1].kind=='BLACK'))){
            posibalLocations.push([this.row-1,this.colom+1])
        }
        if((this.row<7)&&(bord[this.row+1][this.colom]==null||(bord[this.row+1][this.colom]!=null&&bord[this.row+1][this.colom].kind=='BLACK'))){
            posibalLocations.push([this.row+1,this.colom])
        }
        if((this.row<7&&this.colom>0)&&(bord[this.row+1][this.colom-1]==null||(bord[this.row+1][this.colom-1]!=null&&bord[this.row+1][this.colom-1].kind=='BLACK'))){
            posibalLocations.push([this.row+1,this.colom-1])
        }
        if((this.row<7&&this.colom<7)&&(bord[this.row+1][this.colom+1]==null||(bord[this.row+1][this.colom+1]!=null&&bord[this.row+1][this.colom+1].kind=='BLACK'))){
            posibalLocations.push([this.row+1,this.colom+1])
        }
        if((this.colom<7)&&(bord[this.row][this.colom+1]==null||(bord[this.row][this.colom+1]!=null&&bord[this.row][this.colom+1].kind=='BLACK'))){
            posibalLocations.push([this.row,this.colom+1])
        }
        if((this.colom>0)&&(bord[this.row][this.colom-1]==null||(bord[this.row][this.colom-1]!=null&&bord[this.row][this.colom-1].kind=='BLACK'))){
            posibalLocations.push([this.row,this.colom-1])
        }
      }
      if(this.type=='Queen'){
        posibalLocations=[]
        for(let i=this.row+1,j=this.colom+1;i<8&&j<8;i++,j++){
          if(bord[i][j]!=null&&bord[i][j].kind=='BLACK'){
            posibalLocations.push([i,j])
            break;
          }
          if(bord[i][j]!=null)
            break;
          posibalLocations.push([i,j])
        }  
        for(let i=this.row-1,j=this.colom-1;i>=0&&j>=0;i--,j--){
          if(bord[i][j]!=null&&bord[i][j].kind=='BLACK'){
            posibalLocations.push([i,j])
            break;
          }
          if(bord[i][j]!=null)
            break;
          posibalLocations.push([i,j])
        }
        for(let i=this.row+1,j=this.colom-1;i<8&&j>=0;i++,j--){
          if(bord[i][j]!=null&&bord[i][j].kind=='BLACK'){
            posibalLocations.push([i,j])
            break;
          }
          if(bord[i][j]!=null)
            break;
          posibalLocations.push([i,j])
        }
        for(let i=this.row-1,j=this.colom+1;i>=0&&j<8;i--,j++){
          if(bord[i][j]!=null&&bord[i][j].kind=='BLACK'){
            posibalLocations.push([i,j])
            break;
          }
          if(bord[i][j]!=null)
            break;
          posibalLocations.push([i,j])
        }
        for(let i=this.colom+1;i<8;i++){
          if(bord[this.row][i]!=null){
            if(bord[this.row][i].kind=='BLACK'){
                posibalLocations.push([this.row,i])
              break;
            } 
              break;
          }
          posibalLocations.push([this.row,i])
        }
        for(let i=this.colom-1;i>=0;i--){
          if(bord[this.row][i]!=null){
            if(bord[this.row][i].kind=='BLACK'){
                posibalLocations.push([this.row,i])
              break;
            } 
              break;
          }
          posibalLocations.push([this.row,i])
        }
        for(let i=this.row+1;i<8;i++){
          if(bord[i][this.colom]!=null){
            if(bord[i][this.colom].kind=='BLACK'){
                posibalLocations.push([i,this.colom])
              break;
            } 
              break;
          }
          posibalLocations.push([i,this.colom])
        }
        for(let i=this.row-1;i>=0;i--){
          if(bord[i][this.colom]!=null){
            if(bord[i][this.colom].kind=='BLACK'){
                posibalLocations.push([i,this.colom])
              break;
            } 
              break;
          }
          posibalLocations.push([i,this.colom])
        }
      }
      if(this.type=='Runer'){
        posibalLocations=[]
        for(let i=this.row+1,j=this.colom+1;i<8&&j<8;i++,j++){
          if(bord[i][j]!=null&&bord[i][j].kind=='BLACK'){
            posibalLocations.push([i,j])
            break;
          }
          if(bord[i][j]!=null)
            break;
          posibalLocations.push([i,j])
        }  
        for(let i=this.row-1,j=this.colom-1;i>=0&&j>=0;i--,j--){
          if(bord[i][j]!=null&&bord[i][j].kind=='BLACK'){
            posibalLocations.push([i,j])
            break;
          }
          if(bord[i][j]!=null)
            break;
          posibalLocations.push([i,j])
        }
        for(let i=this.row+1,j=this.colom-1;i<8&&j>=0;i++,j--){
          if(bord[i][j]!=null&&bord[i][j].kind=='BLACK'){
            posibalLocations.push([i,j])
            break;
          }
          if(bord[i][j]!=null)
            break;
          posibalLocations.push([i,j])
        }
        for(let i=this.row-1,j=this.colom+1;i>=0&&j<8;i--,j++){
          if(bord[i][j]!=null&&bord[i][j].kind=='BLACK'){
            posibalLocations.push([i,j])
            break;
          }
          if(bord[i][j]!=null)
            break;
          posibalLocations.push([i,j])
        }
      }
      if(this.type=='Soldier'){
        posibalLocations=[]
        if(this.row==6){
          if((this.row>1)&&bord[this.row-1][this.colom]==null&&bord[this.row-2][this.colom]==null){
            posibalLocations.push([this.row-2,this.colom])
          }
        }
        if((this.row>0&&this.colom>0)&&bord[this.row-1][this.colom-1]!=null&&bord[this.row-1][this.colom-1].kind=='BLACK'){
          posibalLocations.push([this.row-1,this.colom-1])
        }
        if((this.row>0&&this.colom<7)&&bord[this.row-1][this.colom+1]!=null&&bord[this.row-1][this.colom+1].kind=='BLACK'){
          posibalLocations.push([this.row-1,this.colom+1])
        }
        if((this.row>0)&&bord[this.row-1][this.colom]==null){
            posibalLocations.push([this.row-1,this.colom])
        }
      }
      if(this.type=='Steeple'){
        posibalLocations=[]
        for(let i=this.colom+1;i<8;i++){
          if(bord[this.row][i]!=null){
            if(bord[this.row][i].kind=='BLACK'){
              posibalLocations.push([this.row,i])
              break;
            } 
              break;
          }
          posibalLocations.push([this.row,i])
        }
        for(let i=this.colom-1;i>=0;i--){
          if(bord[this.row][i]!=null){
            if(bord[this.row][i].kind=='BLACK'){
              posibalLocations.push([this.row,i])
              break;
            } 
              break;
          }
          posibalLocations.push([this.row,i])
        }
        for(let i=this.row+1;i<8;i++){
          if(bord[i][this.colom]!=null){
            if(bord[i][this.colom].kind=='BLACK'){
              posibalLocations.push([i,this.colom])
              break;
            } 
              break;
          }
          posibalLocations.push([i,this.colom])
        }
        for(let i=this.row-1;i>=0;i--){
          if(bord[i][this.colom]!=null){
            if(bord[i][this.colom].kind=='BLACK'){
              posibalLocations.push([i,this.colom])
              break;
            } 
              break;
          }
          posibalLocations.push([i,this.colom])
        }
      }
    }
    return posibalLocations;
  }
  this.showPosibalLocations=function(){
    posibalLocations=this.movingOpsions();
    for(let i=0;i<posibalLocations.length;i++){
      if(bord[posibalLocations[i][0]][posibalLocations[i][1]]!=null&&bord[posibalLocations[i][0]][posibalLocations[i][1]].kind!=this.kind){
        stroke(255,0,0,160);
        strokeWeight(3);
        noFill();
        circle(posibalLocations[i][1]*width/8+(width/16),((height-width)/2+(posibalLocations[i][0])*width/8)+(width/16),width/8-4);
      }
      else{
        noStroke();
        fill('green');
        circle(posibalLocations[i][1]*width/8+(width/16),((height-width)/2+(posibalLocations[i][0])*width/8)+(width/16),width/8/4);
      }
    }
  }
  this.show=function(){
  image(this.color,this.colom*(width/8)+(width/40)/2,((height-width)/2)+(width/8)*this.row+(width/40)/2,(width/8)-(width/40),(width/8)-(width/40));
}
}